### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by seemajune** [learn-co-curriculum/angular-make-our-app-di-safe-lab#3]
might be good to remind the reader to run **npm install *\* each and then **karma start** each time they open a lab that includes a test

**Comment by aturkewi** [comment]
Thanks @seemajune. Since you raised this issue, it looks like `learn` has been updated so that neither of those commands is needed. :)

@PeterBell @ipc103 This alright to close guys?

**Comment by PeterBell** [comment]
Sound good to me @aturkewi let's close this out!
